version: '3'

services:

  gateway-service:
    build: ../gateway
    container_name: gateway-service
    ports:
      - '${GATE_WAY_PORT}:${GATE_WAY_PORT}'
    expose:
      - '${GATE_WAY_PORT}'

  front-end:
    build: ../frontend
    container_name: frontend
    ports:
      - '${FRONT_END_PORT}:80'
    expose:
      - '${FRONT_END_PORT}'


  stocky-service-db:
    image: ${STOCKY_SERVICE_DB_IMAGE_NAME}
    container_name: ${STOCKY_SERVICE_DB_CONTAINER_NAME}
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "${STOCKY_SERVICE_DB_PORT}:${STOCKY_SERVICE_DB_PORT}"
    environment:
      - MYSQL_DATABASE=${STOCKY_SERVICE_DB_NAME}
      - MYSQL_USER=${STOCKY_SERVICE_DB_USER}
      - MYSQL_PASSWORD=${STOCKY_SERVICE_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${STOCKY_SERVICE_DB_PASSWORD_ROOT}

  stocky-service-back:
    build: ${STOCKY_SERVICE_PROJECT_PATH}
    container_name: ${STOCKY_SERVICE_CONTAINER_NAME}
    image: ${STOCKY_SERVICE_IMAGE_NAME}
    ports:
      - "${STOCKY_SERVICE_BACK_PORT}:${STOCKY_SERVICE_BACK_PORT}"
    environment:
      - STOCKY_SERVICE_DB_URL=jdbc:mysql://stocky-service-db:3306/${STOCKY_SERVICE_DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - STOCKY_SERVICE_DB_USER=${STOCKY_SERVICE_DB_USER}
      - STOCKY_SERVICE_DB_PASSWORD=${STOCKY_SERVICE_DB_PASSWORD}
    depends_on:
      - stocky-service-db



  collaborator-service-db:
    image: ${COLLABORATOR_SERVICE_DB_IMAGE_NAME}
    container_name: ${COLLABORATOR_SERVICE_DB_CONTAINER_NAME}
    volumes:
      - app-data:/var/lib/postgresql/data
    ports:
      - "${COLLABORATOR_SERVICE_DB_PORT}:${COLLABORATOR_SERVICE_DB_PORT}"
    environment:
      - POSTGRES_DB=${COLLABORATOR_SERVICE_DB_NAME}
      - POSTGRES_USER=${COLLABORATOR_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${COLLABORATOR_SERVICE_DB_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${COLLABORATOR_SERVICE_DB_PASSWORD_ROOT}

  collaborator-service-back:
    build: ${COLLABORATOR_SERVICE_PROJECT_PATH}
    container_name: ${COLLABORATOR_SERVICE_CONTAINER_NAME}
    image: ${COLLABORATOR_SERVICE_IMAGE_NAME}
    ports:
      - "${COLLABORATOR_SERVICE_BACK_PORT}:${COLLABORATOR_SERVICE_BACK_PORT}"
    environment:
      - COLLABORATOR_SERVICE_DB_URL=jdbc:mysql://collaborator-service-db:5432/${COLLABORATOR_SERVICE_DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - COLLABORATOR_SERVICE_DB_USER=${COLLABORATOR_SERVICE_DB_USER}
      - COLLABORATOR_SERVICE_DB_PASSWORD=${COLLABORATOR_SERVICE_DB_PASSWORD}
    depends_on:
      - collaborator-service-db



volumes:
  app-data:


